name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: macos-14
    # runner images reference info:
    # https://github.com/actions/runner-images/tree/main/images/macos
    steps:
      - uses: actions/checkout@v3

      # default Xcode for macOS 14 image is v15.0.1
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: get xcode information
        run: |
         xcodebuild -version
         swift --version

      - name: Swift tests
        run: swift test

      - name: Integration tests
        run: ./IntegrationTests/scripts/serial_tests.bash

      #- name: Show Build Settings
      #  run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks
      # iOS 17.0.1, iOS 17.2, macOS 13.3 on macOS-13 w/ Xcode 15.2
      # iOS 17.0.1, iOS 17.4 on macOS-14 w/ Xcode 15.3

      - name: Show Destinations
        run: xcodebuild -showdestinations -scheme 'automerge-repo'

      - name: iOS build for MeetingNotes
        # Xcode 15.3 settings
        run: xcodebuild clean build -scheme 'automerge-repo' -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 14' -sdk iphonesimulator17.4




